"""empty message

Revision ID: a3ab06c9b1ae
Revises: 
Create Date: 2020-10-20 22:15:33.948089

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ab06c9b1ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('q1_answer', sa.Integer(), nullable=True),
    sa.Column('q2_answer', sa.Integer(), nullable=True),
    sa.Column('q3_answer', sa.Integer(), nullable=True),
    sa.Column('q4_answer', sa.String(length=5000), nullable=True),
    sa.Column('q5_answer', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['q1_answer'], ['q1_answer.id'], ),
    sa.ForeignKeyConstraint(['q2_answer'], ['q2_answer.id'], ),
    sa.ForeignKeyConstraint(['q3_answer'], ['q3_answer.id'], ),
    sa.ForeignKeyConstraint(['q5_answer'], ['q5_answer.id'], ),
    sa.ForeignKeyConstraint(['variant'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_responses')
    op.drop_table('flask_dance_oauth')
    # ### end Alembic commands ###
